statelite support
git-svn-id: http://xcat.svn.sourceforge.net/svnroot/xcat/xcat-core/branches/2.3@4805 35838ccf-6b3d-0410-a007-ed7a3c9b06b9

diff --git a/xCAT-server/share/xcat/netboot/rh/genimage b/xCAT-server/share/xcat/netboot/rh/genimage
--- a/xCAT-server/share/xcat/netboot/rh/genimage
+++ b/xCAT-server/share/xcat/netboot/rh/genimage
@@ -46,6 +46,8 @@ my $srcdir_otherpkgs;
 my $otherpkglist;
 my $postinstall_filename;
 my $rootimg_dir;
+my $rwfiles;   # these files are used by statelite for tmpfs rw
+
 
 sub xdie {
    system("rm -rf /tmp/xcatinitrd.$$");
@@ -62,7 +64,8 @@ GetOptions(
    'r=s' => \$othernics,
    'l=s' => \$rootlimit,
    't=s' => \$tmplimit,
-   'k=s' => \$kernelver
+   'k=s' => \$kernelver,
+   'm=s' => \$mode
 );
 if (@ARGV > 0) {
     $imagename=$ARGV[0];
@@ -149,15 +152,18 @@ if (!$destdir)
 }
 $rootimg_dir="$destdir/rootimg";
 
+
 unless ($osver and $profile and $netdriver and $prinic) {
-   print 'Usage: genimage -i <nodebootif> -n <nodenetdrivers> [-r <otherifaces>] -o <OSVER> -p <PROFILE> -k <KERNELVER>'."\n";
+   print 'Usage: genimage -i <nodebootif> -n <nodenetdrivers> [-r <otherifaces>] -o <OSVER> -p <PROFILE> -k <KERNELVER> -m <mode>'."\n";
    print '       genimage -i <nodebootif> -n <nodenetdrivers> [-r <otherifaces>] -k <KERNELVER> <imagename>'."\n";
    print "Examples:\n";
    print " genimage -i eth0 -n tg3 -o centos5.1 -p compute\n";
    print " genimage -i eth0 -r eth1,eth2 -n tg3,bnx2 -o centos5.1 -p compute\n";
+   print " genimage -i eth0 -n igb,e1000e,e1000,bnx2,tg3 -o centos5.4 -p nfsroot -m statelite\n";
    print " genimage -i eth0 -n tg3 myimage\n";
    exit 1;
 }
+
 my @ndrivers;
 foreach (split /,/,$netdriver) {
    unless (/\.ko$/) {
@@ -167,6 +173,14 @@ foreach (split /,/,$netdriver) {
       next;
    }
    push @ndrivers,$_;
+}
+if($mode eq "statelite"){
+	push @ndrivers,"fscache.ko";
+	push @ndrivers,"sunrpc.ko";
+	push @ndrivers,"lockd.ko";
+	push @ndrivers,"nfs_acl.ko";
+	push @ndrivers,"nfs.ko";
+
 }
 
 unless ($onlyinitrd) {
@@ -188,6 +202,8 @@ unless ($onlyinitrd) {
    $repnum-=1;
    close($yumconfig);
    mkpath "$rootimg_dir/etc";
+
+
    my $fd;
    open($fd,">>","$rootimg_dir/etc/fstab");
    print $fd "#Dummy fstab for rpm postscripts to see\n";
@@ -332,6 +348,33 @@ if (($postinstall_filename) && (-x $postinstall_filename)) {
     }
 }
 
+
+# statelite .statelite directory added here.
+# this is where tmpfs will be created.
+if($mode eq "statelite"){
+	mkpath "$rootimg_dir/.statelite";  # create place for NFS mounts.	
+	# this script will get the directories.	
+	unless(-f "../add-on/statelite/rc.statelite"){
+		print "Can't find ../add-on/statelite/rc.statelite!\n";
+		exit;
+	}
+	system("cp ../add-on/statelite/rc.statelite $rootimg_dir/etc/init.d/statelite");
+	# also need to add this file:
+	# may have already been made into a symbolic link, if so ignore it
+
+	unless(-l "$rootimg_dir/var/lib/dhclient" ){
+		mkpath "$rootimg_dir/var/lib/dhclient/";
+		system("touch $rootimg_dir/var/lib/dhclient/dhclient-$prinic.leases");
+	}
+
+	unless(-l "$rootimg_dir/var/lib/dhcp" ){
+		mkpath "$rootimg_dir/var/lib/dhcp/";
+		system("touch $rootimg_dir/var/lib/dhcp/dhclient-$prinic.leases");
+	}
+}   
+
+
+
 mkinitrd();
 
 sub getlibs {
@@ -385,8 +428,106 @@ sub mkinitrd {
 	mkpath("/tmp/xcatinitrd.$$/etc/ld.so.conf.d");
 	mkpath("/tmp/xcatinitrd.$$/var/lib/dhclient");
 	my $inifile;
+
+# start writing to the init script.
 	open($inifile,">","/tmp/xcatinitrd.$$/init");
 	print $inifile "#!/sbin/busybox.anaconda sh\n";
+
+# add some functions
+ 	print $inifile <<EOS1;
+NEWROOT="/sysroot"
+SHELL="/bin/sh"
+RWDIR=".statelite"
+
+
+# Define some colors
+RESET="\033[0m"
+RED="\033[31m"
+CYAN="\033[36m"
+YELLOW="\033[33m\033[1m"
+GREEN="\033[32m"
+PINK="\033[35m\033[1m"
+MAGENTA="\033[35m"
+BROWN="\033[33m"
+NORMAL=\$RESET
+
+# This function is used to mount files/directories from the .statelite directory 
+#  over the root directory.
+# This function stolen from redhat
+shell() {
+        echo ''
+        echo -e "\$YELLOW Entering rescue/debug init shell."
+        echo -e " Exit shell to continue booting.\$RESET"
+        \$SHELL
+}
+mountfile () {
+    snapshotfile=\${NEWROOT}/\${RWDIR}/\${2}\${1}
+    dir=`dirname \$snapshotfile`
+#
+#  Check if file already exists in snapshot directory.  If not attempt to copy
+#    from root directory to snapshot directory.
+#
+    if [ ! -e \$snapshotfile ]; then
+        mkdir -p \$dir || echo -e "\${RED}Can't make \$dir\${NORMAL}"
+        #echo -e "\${YELLOW} \${1} missing from client specific area.\${RESET}"
+        if [ -e \$NEWROOT/\${1} ] ; then
+            #echo "Copying \${1}"
+            rsync -a \$NEWROOT/\${1} \$snapshotfile
+        else
+            #echo "Creating \${1}"
+            touch \$snapshotfile
+        fi
+    fi
+#
+#  Mount the snapshotfile over the root file so the client will have r/w access
+#
+    mount -n -o bind \$NEWROOT/\$RWDIR/\${2}\${1} \$NEWROOT/\${1}
+}
+
+fancydisplay () {
+        clear
+        echo -e "\$CYAN"
+echo '
+             ..                                               :iiii,
+           :tLL;                                             .,:...,.
+          .j;:tLt.   :.                               .;j:   ij::::;.
+        :tt;:::,ii:.jEEGi                           :tDEEG:.ti,::::;t:
+       .,,,,,,,,,,,tLEEEEj:                        tDEEEEDtj;,,,::::::
+        .:,,::::::,;fDEEEEEL,.                .,ijDEDDDEEGt,,,,:,ijj;
+          ....   ..:;jDDLGDEEEGGGfjjjjjjfffLGDEEDEEDLjfGDt,:..
+                     .iftffGDLLDEEEDDDEEDDDDEDEEGLfLjjtti:
+                       ,fii;jGDGffLjifLGLjtfffffGDEDGfji
+                        ;DEEGffDDDjiii;;ii;,tGDEGjfEEEEf.
+                       ,GEGGftiGEEEDt:,;,;;LEEDGjLEEEEEEG
+                      ;DEDGjtjfitjGGjfDGj;jLLiitfGDEGjEEDj
+                      fGjjtfLfji;itjfGDjLDfjjjji;tGGLDEEDj
+                      fEDGffjti;ittjjjjtjjjjt:,,iiGGGGjtf.
+                      :fGGLfLLfLGf;i;ijffj,,tjLGDDGLfjtf,
+                    :;tLfjiiffLGDDDGLGEEEEjfGDDGGLfjfff:
+             .. ,;tLLLLLL,;tijfLGGGjfDEEEEDLLGGGLLLjtjLLfi,.
+         .jffLLLLGGLfjj;:  :,;ijLGLfjGEDDEGtfGGLfjj:.,jjLGGLti;,,;fj,
+         ,fGGGGGGLj,.          ;jGGGGLLjffftjLj;..     .,tfGGGGGGGGGGi
+          ,jGDDDj,.              :tLGLGGLGDLjt,           :iLGGDDDDGLif
+          ,LDDDL,                 .;LDDDDGfff,              ,;iGDDj;,..
+          ;fGGGf,                    ,;;;;,:                 tf;jL,
+           ;.:::,               Powered by xCAT               ,j.:;
+'
+        echo -e "\$RESET"
+        echo -e "\$YELLOW"
+echo '
+                            _________     ________________
+                     ___  __\\_   ___ \\   /  _  \\__    ___/
+                     \\  \\/  /    \\  \\/  /  /_\\  \\|    |   
+                      >    <\\     \\____/    |    \\    |   
+                     /__/\\_ \\\\______  /\\____|__  /____|   
+                           \\/       \\/         \\/         
+'
+        echo -e "\$RESET"
+}
+
+EOS1
+
+
 	print $inifile "busybox.anaconda mount -t proc /proc /proc\n";
 	print $inifile "busybox.anaconda --install\n";
 	print $inifile "mount -t sysfs /sys /sys\n";
@@ -423,9 +564,11 @@ sub mkinitrd {
       print $inifile "insmod /lib/$_\n";
    }
    print $inifile <<EOMS;
+# check and see if debug is specified on command line
+grep '\(debug\)' /proc/cmdline > /dev/null && export DEBUG=1
 netstart
 while ! ifconfig | grep inet; do
-    echo Failed to acquire address, retrying
+    echo -e "\${RED}Failed to acquire address, retrying \${RESET}"
     sleep 1
     netstart
 done
@@ -443,7 +586,8 @@ for i in `cat /proc/cmdline`; do
         while [ ! -r "\$FILENAME" ]; do
           echo Getting \$VALUE...
           if ! wget \$VALUE; then
-            sleep 5 #should be random, exponential for scale
+            ST=`expr \$RANDOM % 5`
+            sleep \$ST
             rm -f \$FILENAME
           fi
         done
@@ -454,9 +598,185 @@ for i in `cat /proc/cmdline`; do
         SERVER=`echo \$VALUE|awk -F/ '{print \$3}'`
         ROOTDIR=`echo \$VALUE|awk -F/ '{for(i=4;i<=NF;i++) printf "/%s",\$i}'`
       fi
+   # for NFS root 
+   elif [ "\$KEY" == 'NFSROOT' ]; then
+	NFSROOT=1
+	VALUE=`echo \$i |awk -F= '{print \$2}'`
+	SERVER=`echo \$VALUE|awk -F: '{print \$1}'`
+	ROOTDIR=`echo \$VALUE|awk -F/ '{for(i=2;i<=NF;i++) printf "/%s",\$i}'`
+   elif [ "\$KEY" == 'STATEMNT' ]; then
+	NFSROOT=1
+	VALUE=`echo \$i |awk -F= '{print \$2}'`
+	SNAPSHOTSERVER=`echo \$VALUE|awk -F: '{print \$1}'`
+	SNAPSHOTROOT=`echo \$VALUE|awk -F/ '{for(i=2;i<=NF;i++) printf "/%s",\$i}'`
+	# may be that there is not server and just a directory.
+	if [ -z \$SNAPSHOTROOT ]
+	then
+		 SNAPSHOTROOT=\$SNAPSHOTSERVER
+		SNAPSHOTSERVER=
+	fi
    fi
 done
+
+# show xCAT logo
+fancydisplay
+
+
 echo 0 > /proc/sys/vm/zone_reclaim_mode #Avoid kernel bug
+
+# NFSROOT code here:
+if [ "\$NFSROOT" = "1" ]; then
+	echo Setting up Statelite
+	# for loop back mounting capability!
+	mknod /dev/loop0 b 7 0
+	mkdir -p \$NEWROOT
+ 	MAXTRIES=5
+	ITER=0
+	ME=`hostname`
+	while ! mount.nfs \${SERVER}:\${ROOTDIR}/rootimg \$NEWROOT -r -n -o nolock,rsize=32768,udp,nfsvers=3,timeo=14
+	do
+		ITER=\$(expr \$ITER + 1)
+		if [ "\$ITER" == "\$MAXTRIES" ]
+      		then
+				echo "You're dead.  rpower \$ME boot to play again."
+				echo "Possible problems:
+1.  This initrd wasn't created for statelite node?  rerun genimage with the -m statelite flag, then rerun 'nodeset \$ME statelite'
+2.  Is DNS set up?  Maybe that's why I can't mount \${SERVER}.
+3.  The nfs modules aren't set right in this initfs?"
+    
+			shell
+			exit
+		fi
+		echo -e "\${RED}Could not mount \$SERVER:\$ROOTDIR on \$NEWROOT \$RESET"
+		RS=`expr \$RANDOM % 30`
+		echo -e "Trying again in \$RS seconds"
+		sleep \$RS
+	done
+
+# now we need to mount the rest of the system.  This is the read/write portions
+#echo "Mounting Snapshot directories"
+
+	if [ ! -e "\$NEWROOT/\$RWDIR" ]
+	then
+		echo ""
+		echo -e "\${RED}Hmmm... this NFS root directory doesn't have a /\$RWDIR directory for me to mount a rw filesystem.  You'd better create it... \${NORMAL}"
+		echo "."
+		shell
+	fi
+
+	while [ ! -e "\$NEWROOT/etc/init.d/statelite" ]
+	do
+		echo ""
+		echo -e "\${RED}Hmmm... \$NEWROOT/etc/init.d/statelite doesn't exist.  Perhaps you didn't create this image with the -m statelite mode"
+		echo ""
+		shell
+	done
+	grep '\\(shell\\)' /proc/cmdline >/dev/null && shell
+	mount -t tmpfs rw \$NEWROOT/\$RWDIR
+	mkdir -p \$NEWROOT/\$RWDIR/tmpfs
+
+
+	# mount the SNAPSHOT directory here for persistent use.
+	if [ ! -z \$SNAPSHOTSERVER ]
+	then
+		mkdir -p \$NEWROOT/\$RWDIR/persistent
+ 		MAXTRIES=5
+		ITER=0
+		while ! mount \$SNAPSHOTSERVER:\$SNAPSHOTROOT  \$NEWROOT/\$RWDIR/persistent
+		do
+			ITER=\$(expr \$ITER + 1)
+			if [ "\$ITER" == "\$MAXTRIES" ]
+      			then
+				echo "You're dead.  rpower \$ME boot to play again."
+				echo "Possible problems:
+1.  \$SNAPSHOTSERVER is not exporting \$SNAPSHOTROOT ?
+2.  Is DNS set up?  Maybe that's why I can't mount \$SNAPSHOTSERVER."
+				shell
+				exit
+			fi
+			echo -e "\${RED}Hmmm... Can't mount \$SNAPSHOTSERVER:\$SNAPSHOTROOT. \${NORMAL}"
+			RS=`expr \$RANDOM % 20`
+			echo -e "Trying again in \$RS seconds"
+			sleep \$RS	
+		done
+	fi
+
+	grep '\\(shell\\)' /proc/cmdline >/dev/null && shell
+
+	# have to preserve the initial DHCP request.  So we link it.
+
+	if [ ! -d \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhclient ]
+	then
+		mkdir -p \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhclient
+	fi
+	if [ ! -d \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhcp ]
+	then
+		mkdir -p \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhcp
+	fi
+
+	cp -fp /var/lib/dhclient/dhclient.leases \${NEWROOT}/\${RWDIR}/tmpfs/var/lib/dhclient/dhclient-$prinic.leases
+	cp -fp /var/lib/dhclient/dhclient.leases \${NEWROOT}/\${RWDIR}/tmpfs/var/lib/dhcp/dhclient-$prinic.leases
+
+	# dhclient
+	#while ! mount -n --bind \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhclient/dhclient-$prinic.leases \$NEWROOT/var/lib/dhclient/dhclient-$prinic.leases
+	#do
+	#	echo "Can't mount /tmpfs/var/lib/dhclient/dhclient-$prinic.leases to /var/lib/dhclient/dhclient-$prinic.leases"
+	#	shell
+	#done
+
+	# dhcp
+	#while ! mount -n --bind \$NEWROOT/\$RWDIR/tmpfs/var/lib/dhcp/dhclient-$prinic.leases \$NEWROOT/var/lib/dhcp/dhclient-$prinic.leases
+	#do
+	#	echo "Can't mount /tmpfs/var/lib/dhcp/dhclient-$prinic.leases to /var/lib/dhcp/dhclient-$prinic.leases"
+	#	shell
+	#done
+
+	
+
+	[ -e /etc/ntp.conf ] && mkdir -p \$NEWROOT/\$RWDIR/tmpfs/etc && cp /etc/ntp.conf \$NEWROOT/\$RWDIR/tmpfs/etc/ 
+
+	
+	[ -e /etc/ntp/step-kickers ] && mkdir -p \$NEWROOT/\$RWDIR/tmpfs/etc/ntp && cp /etc/ntp/step-kickers \$NEWROOT/\$RWDIR/tmpfs/etc/ntp 
+
+	
+	[ -e /etc/resolv.conf ] && mkdir -p \$NEWROOT/\$RWDIR/tmpfs/etc && cp /etc/resolv.conf \$NEWROOT/\$RWDIR/tmpfs/etc/ 
+
+	# now that everything is mounted, lets do this
+	# hmmm, apparently I'm checking this twice... so I'd better
+	# be really sure the file is there.
+	while [ -z \$NEWROOT/etc/init.d/statelite ]
+	do
+		echo "\$NEWROOT/etc/init.d/statelite does not exist in image!"
+		shell
+	done
+
+	# do all the mounts:
+	\$NEWROOT/etc/init.d/statelite	
+
+	# give the debug shell just before we go if specified!
+	grep '\(shell\)' /proc/cmdline > /dev/null && shell
+
+	echo 0x100 > /proc/sys/kernel/real-root-dev
+	export keep_old_ip=yes
+	export fastboot=yes
+	export READONLY=yes
+	grep '\\(shell\\)' /proc/cmdline >/dev/null && shell
+	mount -n --bind /dev /sysroot/dev
+	umount /sys
+	umount /proc
+
+	if ! exec /sbin/switch_root -c /dev/console \$NEWROOT /sbin/init
+	then
+		echo ""
+		echo -e "\${RED}Couldn't switch_root.  Something must be wrong with NFS root image.\${RESET}"
+	#	mount -t proc proc /proc
+		shell
+	fi
+	exit
+fi
+# END NFSROOT/Statelite code
+
+# RAM root Hybrid with NFS root
 if [ "\$NFS" = "1" ]; then
   echo Setting up nfs with ram overlay.
   mknod /dev/loop0 b 7 0
@@ -466,7 +786,8 @@ if [ "\$NFS" = "1" ]; then
   while [ ! -d /ro/bin ]; do
     echo mounting \$SERVER:\$ROOTDIR on /ro
     mount.nfs \$SERVER:\$ROOTDIR /ro -r -n -o nolock,rsize=32768,udp,nfsvers=3,timeo=14
-    sleep 5 #should be random, exponential for scale
+    ST=`expr \$RANDOM % 5`
+    sleep \$ST
   done
   mount -t tmpfs rw /rw
   mkdir -p /rw/etc
@@ -536,6 +857,11 @@ EOMS
    print $inifile "mknod /sysroot/dev/console c 5 1\n";
    print $inifile "exec switch_root -c /dev/console /sysroot /sbin/init\n";
    close($inifile);
+
+
+
+
+
    open($inifile,">"."/tmp/xcatinitrd.$$/bin/netstart");
    print $inifile "#!/sbin/nash\n";
    print $inifile "network --device $prinic --bootproto dhcp\n";
@@ -550,8 +876,8 @@ EOMS
          push @filestoadd,[$_,"lib/$_"];
      }
    }
-
-   foreach ("bin/cpio","sbin/nash","sbin/busybox.anaconda","sbin/rmmod","sbin/mount.nfs") {
+   # add rsync for statelite
+   foreach ("bin/cpio","sbin/nash","sbin/busybox.anaconda","sbin/rmmod","sbin/mount.nfs","/usr/bin/rsync") {
       getlibs($_);
       push @filestoadd,$_;
    }
@@ -728,9 +1054,7 @@ sub generic_post { #This function is meant to leave the image in a state approxi
    chmod(0755,"$rootimg_dir/etc/rc3.d/S60gettyset");
    #link("$rootimg_dir/sbin/init","$rootimg_dir/init");
    
-   rename(<$rootimg_dir/boot/vmlinuz*>,"$destdir/kernel");
-}
-
+   rename(<$rootimg_dir/boot/vmlinuz*>,"$destdir/kernel"); } 
 
 #get th extra package name
 sub get_extra_package_names {
@@ -848,9 +1172,25 @@ sub get_pkglist_file_name {
    } elsif (-r "$base/$profile.pkglist") {
       return "$base/$profile.pkglist";
    } 
-
    return "";
 }
+
+sub get_rwfiles_file_name {
+   my $base=shift;
+   if (-r "$base/$profile.$osver.$arch.rwfiles") {
+      return "$base/$profile.$osver.$arch.rwfiles";
+   } elsif (-r "$base/$profile.$arch.rwfiles") {
+      return "$base/$profile.$arch.rwfiles";
+   } elsif (-r "$base/$profile.$osver.rwfiles") {
+      return "$base/$profile.$osver.rwfiles";
+   } elsif (-r "$base/$profile.rwfiles") {
+      return "$base/$profile.rwfiles";
+   } 
+   return "";
+}
+
+
+
 
 sub get_postinstall_file_name {
    my $base=shift;
@@ -867,3 +1207,4 @@ sub get_postinstall_file_name {
    return "";
 }
 
+	
